### ISSUE TITLE
Actions do not work when selecting a record

### ISSUE THREAD

**Issue by DanOliveira98** [Lupennat/nova-expandable-many#6]
When selecting the records, it would be interesting to bring the actions to be executed by the expandable.

![image](https://github.com/Lupennat/nova-expandable-many/assets/38472540/ae4b3449-b903-47df-bfb4-861e7ee531c6)

**Comment by Lupennat** [comment]
Hi DanOliveira,
Sorry for my late reply.

The support of actions, relating to different resources, is in fact only managed by Nova in the detail pages and not in the index pages.
This is why I do not envisage support for custom actions, but only for Nova's native actions (replicate, edit, delete, restore).
