### ISSUE TITLE
Expandable in stack doesn't work (Nova v4.34.3)

### ISSUE THREAD

**Issue by Keko-94** [Lupennat/nova-expandable-many#7]
Hey !

The expandable doesn't work if in Stack field :

`Stack::make('Test', [
    HasMany::make('User Post', 'posts', Post::class)->expandable()
]),`

I got an error in the console: 

> TypeError: r.resource is undefined
![image](https://github.com/Lupennat/nova-expandable-many/assets/62820283/3f7d1538-6544-4c8a-9776-42a274ab932a)

Thank you very much !

**Comment by Lupennat** [comment]
Hi keko,
Thank's for your feedback.
From Nova's documentation, Stack fields are only intended for stacking text lines.
For this reason, expandable fields cannot be used within Stack fields and I do not plan to implement support for them.
